### ISSUE TITLE
xsinator ssl cert expired on December 7th

### ISSUE THREAD

**Issue by miketaylr** [RUB-NDS/xsinator.com#3]
<img width="1147" alt="Screenshot 2022-12-08 at 10 32 56 AM" src="https://user-images.githubusercontent.com/67283/206487924-91e84ded-e0c2-45f8-afdc-ffa3e209abc2.png">

**Comment by NDevTK** [comment]
Looks to be renewed :)
Common Name (CN)	xsinator.com
Organization (O)	<Not Part Of Certificate>
Organizational Unit (OU)	<Not Part Of Certificate>
Common Name (CN)	R3
Organization (O)	Let's Encrypt
Organizational Unit (OU)	<Not Part Of Certificate>
Issued On	Thursday, December 8, 2022 at 2:49:40 PM
Expires On	Wednesday, March 8, 2023 at 2:49:39 PM

**Comment by miketaylr** [comment]
Excellent!
